In [14]:
from jheapq import core
import heapq
from importlib import reload
import jax
import jax.numpy as jnp

In [15]:
!pip install line_profiler

In [16]:
%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


In [39]:
reload(core)
data = jax.random.categorical(jax.random.PRNGKey(0), jnp.ones(150), 
                              shape=(101,)) * 1.
# print(data)
%time heapified = core.heapify_fixedsize(data)
data = jax.random.categorical(jax.random.PRNGKey(3), jnp.ones(150), 
                              shape=(101,)) * 1.
%time heapified = core.heapify_fixedsize(data)
%time heapified2 = core.heapify_fixedsize(data[:-5])
%time heapified3 = core.heapify(data)
%time heapified4 = core.heapify(data[:-5])
jnp.allclose(heapified2, heapified4)

CPU times: user 104 ms, sys: 0 ns, total: 104 ms
Wall time: 100 ms
CPU times: user 20 µs, sys: 6 µs, total: 26 µs
Wall time: 27.9 µs
CPU times: user 84.5 ms, sys: 7.79 ms, total: 92.3 ms
Wall time: 87.6 ms
CPU times: user 96.2 ms, sys: 684 µs, total: 96.9 ms
Wall time: 93.1 ms
CPU times: user 1.39 ms, sys: 389 µs, total: 1.78 ms
Wall time: 1.52 ms


DeviceArray(True, dtype=bool)

In [49]:
reload(core)
%time ret, heapified_ = core.heappop_fixedsize(heapified)
%time ret, rem = core.heappop_fixedsize(heapified_)
%time ret, heapified_ = core.heappop(heapified)
%time ret2, rem2 = core.heappop(heapified_)


CPU times: user 83.1 ms, sys: 0 ns, total: 83.1 ms
Wall time: 81.1 ms
CPU times: user 76.7 ms, sys: 0 ns, total: 76.7 ms
Wall time: 75.4 ms
CPU times: user 59.4 ms, sys: 8.4 ms, total: 67.8 ms
Wall time: 67 ms
CPU times: user 2.26 ms, sys: 499 µs, total: 2.76 ms
Wall time: 2.56 ms


In [38]:

data = jnp.array([])
reload(core)
for i in range(3):
    new_items =  jax.random.categorical(jax.random.PRNGKey(0), 
                                        jnp.ones(150), 
                              shape=(3,))
    for new_item in new_items:
        %time data = core.heappush_fixedsize(data, new_item)
    print(data)

CPU times: user 37.9 ms, sys: 0 ns, total: 37.9 ms
Wall time: 36.3 ms
CPU times: user 41.9 ms, sys: 102 µs, total: 42 ms
Wall time: 40.2 ms
CPU times: user 41.8 ms, sys: 390 µs, total: 42.1 ms
Wall time: 40.3 ms
[  0.  79. 118.]
CPU times: user 39.8 ms, sys: 0 ns, total: 39.8 ms
Wall time: 38 ms
CPU times: user 41.4 ms, sys: 0 ns, total: 41.4 ms
Wall time: 39.6 ms
CPU times: user 44.4 ms, sys: 806 µs, total: 45.2 ms
Wall time: 43 ms
[  0.   0. 118.  79.  79. 118.]
CPU times: user 44.4 ms, sys: 0 ns, total: 44.4 ms
Wall time: 43.4 ms
CPU times: user 43.1 ms, sys: 0 ns, total: 43.1 ms
Wall time: 40.8 ms
CPU times: user 38.8 ms, sys: 1.1 ms, total: 39.9 ms
Wall time: 38.4 ms
[  0.   0.  79.   0.  79. 118. 118.  79. 118.]


In [31]:
reload(core)
data = jnp.array([])
reload(core)
for i in range(3):
    new_items =  jax.random.categorical(jax.random.PRNGKey(0), 
                                        jnp.ones(150), 
                              shape=(3,))
    for new_item in new_items:
        %time data = core.heappush(data, new_item)
    print(data)

CPU times: user 44.8 ms, sys: 0 ns, total: 44.8 ms
Wall time: 44.4 ms
CPU times: user 2.1 ms, sys: 0 ns, total: 2.1 ms
Wall time: 1.7 ms
CPU times: user 1.57 ms, sys: 0 ns, total: 1.57 ms
Wall time: 1.32 ms
[  0.  79. 118.]
CPU times: user 952 µs, sys: 0 ns, total: 952 µs
Wall time: 957 µs
CPU times: user 1.56 ms, sys: 0 ns, total: 1.56 ms
Wall time: 1.32 ms
CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 1.07 ms
[  0.   0. 118.  79.  79. 118.]
CPU times: user 823 µs, sys: 0 ns, total: 823 µs
Wall time: 828 µs
CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 1.14 ms
CPU times: user 1.16 ms, sys: 146 µs, total: 1.3 ms
Wall time: 1.27 ms
[  0.   0.  79.   0.  79. 118. 118.  79. 118.]


In [78]:
data
data2 = jnp.hstack((data, jnp.ones(10) * jnp.inf))
%time print(jax.jit(_siftup)(data, 0, len(data)))
%time print(jax.jit(_siftup)(data2, 0, len(data)))

[ 20  52  97 104  29  25  50  55  40  28]
CPU times: user 477 µs, sys: 137 µs, total: 614 µs
Wall time: 496 µs
[ 20.  52.  97. 104.  29.  25.  50.  55.  40.  28.  inf  inf  inf  inf
  inf  inf  inf  inf  inf  inf]
CPU times: user 575 µs, sys: 164 µs, total: 739 µs
Wall time: 618 µs


In [33]:
data_list = data.tolist()
# print(data_list)
%time heapq.heapify(data_list)
# print(data_list)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 7.63 µs


In [12]:
core.heappush(heapified, 10.5)

DeviceArray([ 0. ,  0. ,  1. ,  0. ,  7. ,  5. , 11. ,  3. , 17. , 11. ,
             10. , 10.5,  8. , 42. , 19. ,  5. , 15. , 57. , 26. , 11. ,
             15. , 22. , 30. , 20. , 13. , 25. , 30. , 77. , 62. , 52. ,
             55. , 35. ,  7. , 46. , 37. , 77. , 65. , 32. , 49. , 20. ,
             28. , 37. , 30. , 22. , 24. , 49. , 31. , 70. , 35. , 48. ,
             80. , 98. , 57. , 99. , 78. , 78. , 92. , 94. , 98. , 63. ,
             79. , 82. , 89. , 67. , 59. , 47. , 48. , 97. , 65. , 57. ,
             68. , 87. , 90. , 73. , 92. , 70. , 36. , 77. , 68. , 80. ,
             79. , 96. , 63. , 96. , 96. , 65. , 93. , 81. , 35. , 89. ,
             40. , 51. , 87. , 46. , 99. , 72. , 95. , 40. , 82. , 87. ,
             53. ], dtype=float32, weak_type=True)

In [36]:
%time heapq.heappush(data_list, 10.5)
print(data_list)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs
[0.0, 0.0, 10.5, 0.0, 10.5, 79.0, 118.0, 79.0, 118.0, 79.0, 10.5, 118.0]


In [21]:
data_list = data.tolist()

for i in reversed(range(len(data_list)//2)):
    heapq._siftup(data_list, i)
    print(i, data_list)

4 [54, 63, 85, 45, 7, 50, 73, 69, 51, 15]
3 [54, 63, 85, 45, 7, 50, 73, 69, 51, 15]
2 [54, 63, 50, 45, 7, 85, 73, 69, 51, 15]
1 [54, 7, 50, 45, 15, 85, 73, 69, 51, 63]
0 [7, 15, 50, 45, 54, 85, 73, 69, 51, 63]


In [ ]:
data_list = data2.tolist()
print(data_list)
heapq._siftdown(data_list, 3, )
print(data_list)